services:

  app:
    build: .
    container_name: agenda-medica-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mock_api
    restart: always


  mock_api:
    build:
      context: ./mock_api
    container_name: agenda-medica-mock-api
    ports:
      - "5001:5001"
    restart: always